### ISSUE TITLE
ModuleNotFoundError: No module named 'src.entropy_models.MLCodec_rans'

### ISSUE THREAD

**Issue by 123world** [DeepMC-DCVC/DCVC#2]
--write_stream
True
--write_recon_frame
True

ModuleNotFoundError: No module named 'src.entropy_models.MLCodec_rans'

![2021-12-21 14-48-33 的屏幕截图](https://user-images.githubusercontent.com/46485739/146884605-7ebd77a5-c17e-41cc-a90d-047f45e96f06.png)

**Comment by rubenamtz-msft** [comment]
What's the solution to this issue? @123world
