### ISSUE TITLE
DCVC models are not available now.

### ISSUE THREAD

**Issue by wsxtyrdd** [DeepMC-DCVC/DCVC#3]
The Onedrive link seems to break down now.

**Comment by DeepMC-DCVC** [comment]
I can access the link via the VPN. But you can download it from the backup link: https://pan.baidu.com/s/1_hMdtdMVWbIeyQnWFzYEcQ 提取码: g6hw

**Comment by wsxtyrdd** [comment]
Thank you! I have to buy a better ladder.
