### ISSUE TITLE
Where is the training script?

### ISSUE THREAD

**Issue by swaiwi** [DeepMC-DCVC/DCVC#4]
Hi, your work is so elegant and powerful and I am very interested about it, could you please provide the training script?

**Comment by DeepMC-DCVC** [comment]
Currently, we will not release the training code. But the detailed training process can be seen in https://proceedings.neurips.cc/paper/2021/file/96b250a90d3cf0868c83f8c965142d2a-Supplemental.pdf

**Comment by LiangHui6** [comment]
Hi,bro：
      Do you accomplish DCVC training code?

**Comment by LiangHui6** [comment]
> Hi, your work is so elegant and powerful and I am very interested about it, could you please provide the training script?
Hi,bro：Do you accomplish DCVC training code?

**Comment by LiangHui6** [comment]
> Currently, we will not release the training code. But the detailed training process can be seen in https://proceedings.neurips.cc/paper/2021/file/96b250a90d3cf0868c83f8c965142d2a-Supplemental.pdf

Hi teacher,if you can provide the training code,your work can help many people who are interested in video compression.
