### ISSUE TITLE
where is the BasketballDrive_1920x1080_50.yuv

### ISSUE THREAD

**Issue by swaiwi** [DeepMC-DCVC/DCVC#5]
where can i find BasketballDrive_1920x1080_50.yuv to make data

**Comment by LiangHui6** [comment]
Hi bro,can you run this code provided by the author?the code only has testing code.

**Comment by DeepMC-DCVC** [comment]
The sequences come from the standard community. The official material can refer JVET-Z0004 (https://jvet-experts.org/doc_end_user/current_document.php?id=11537).
