### ISSUE TITLE
About dataset_config_example.json

### ISSUE THREAD

**Issue by wsxtyrdd** [DeepMC-DCVC/DCVC#7]
Nice work!
A small mistake in dataset_config_example，HEVC_B sequence in dataset_config.json  should be :
"HEVC_B": {
    "base_path": "",
    "sequences": {
        "BasketballPass_384x192_**50**":    {"frames":  100, "gop":  10},
        "BlowingBubbles_384x192_**50**":    {"frames":  100, "gop":  10},
        "BQSquare_384x192_**60**":          {"frames":  100, "gop":  10},
        "RaceHorses_384x192_**30**":        {"frames":  100, "gop":  10}
    }
}
The results are consistent with the paper's curve.

**Comment by LiangHui6** [comment]
hi,bro,Do you run this testing code?

**Comment by DeepMC-DCVC** [comment]
Thanks for your help. We will fix it.
