### ISSUE TITLE
Decoding frame failed when writing stream

### ISSUE THREAD

**Issue by guohf3** [DeepMC-DCVC/DCVC#9]
Dear authors, 
Thanks for your sharing such an excellent model. It is fascinating and innovative. However, I have met a problem when I am opening the writing stream option. As shown in Figure, the decoded frame is almost black except for some areas at the top-left corner. Have you ever had this problem and could you share some experience? Thank you very much.
Looking forward to your reply. 
Best regards
![recon_frame_1](https://user-images.githubusercontent.com/28222131/173762626-4e1fb078-8cc3-4561-be25-ab477fe420a1.png)

**Comment by DeepMC-DCVC** [comment]
This may be caused by the encoding/decoding mismatch. When writing bitstream, you must ensure that the environment is deterministic. 
![image](https://user-images.githubusercontent.com/96097817/173767610-de2bb901-2a94-4b4e-8e4c-84ba529a98d0.png)

In addition, the encoding and decoding need the same PyTorch/python version.

**Comment by guohf3** [comment]
> This may be caused by the encoding/decoding mismatch. When writing bitstream, you must ensure that the environment is deterministic. ![image](https://user-images.githubusercontent.com/96097817/173767610-de2bb901-2a94-4b4e-8e4c-84ba529a98d0.png)
> 
> In addition, the encoding and decoding need the same PyTorch/python version.

Thanks for your reply. Sure, the environment is deterministic. And the encoding and decoding are in the same PyTorch/python version. I used the test_video.py (code in DCVC) to test without any more modification.

**Comment by DeepMC-DCVC** [comment]
Which quality point and the corresponding frame number? I will cross-check it.

**Comment by guohf3** [comment]
Thanks for your reply. The quality point is lambda256 and the frame is P frame. I used the following model to load to test. 
https://drive.google.com/file/d/1RohB08VY4MVI7BK6yl_WcyreCvHuBxNf/view?usp=sharing 
Without writing stream, the reconstructed frame and bin file are correct.

**Comment by DeepMC-DCVC** [comment]
I use `python test_video.py --i_frame_model_name cheng2020-anchor  --i_frame_model_path  checkpoints/cheng2020-anchor-3-e49be189.pth.tar    --test_config     dataset_config_example.json  --cuda true --cuda_device 0,1,2,3   --worker 4   --output_json_result_path  DCVC_result_psnr.json    --model_type psnr  --recon_bin_path recon_bin_folder_psnr --model_path checkpoints/model_dcvc_quality_0_psnr.pth   --write_stream True --write_recon_frame True` to test Beauty_1920x1024_120fps_420_8bit_YUV, the reconstruction is normal and has no bug....

**Comment by guohf3** [comment]
Thanks for your reply.
